mock_response = {
    'cod': '200',
    'message': 0,
    'cnt': 40,
    'list': [
        {
            'dt': 1727190000,
            'main': {
                'temp': 28.11,
                'feels_like': 29.28,
                'temp_min': 28.11,
                'temp_max': 28.98,
                'pressure': 1014,
                'sea_level': 1014,
                'grnd_level': 1011,
                'humidity': 57,
                'temp_kf': -0.87,
            },
            'weather': [
                {
                    'id': 803,
                    'main': 'Clouds',
                    'description': 'nublado',
                    'icon': '04d',
                }
            ],
            'clouds': {'all': 75},
            'wind': {'speed': 6.36, 'deg': 129, 'gust': 7.88},
            'visibility': 10000,
            'pop': 0,
            'sys': {'pod': 'd'},
            'dt_txt': '2024-09-24 15:00:00',
        },
        {
            'dt': 1727200800,
            'main': {
                'temp': 27.99,
                'feels_like': 29.22,
                'temp_min': 27.75,
                'temp_max': 27.99,
                'pressure': 1014,
                'sea_level': 1014,
                'grnd_level': 1010,
                'humidity': 58,
                'temp_kf': 0.24,
            },
            'weather': [
                {
                    'id': 803,
                    'main': 'Clouds',
                    'description': 'nublado',
                    'icon': '04d',
                }
            ],
            'clouds': {'all': 54},
            'wind': {'speed': 6.48, 'deg': 132, 'gust': 8.38},
            'visibility': 10000,
            'pop': 0,
            'sys': {'pod': 'd'},
            'dt_txt': '2024-09-24 18:00:00',
        },
        {
            'dt': 1727211600,
            'main': {
                'temp': 26,
                'feels_like': 26,
                'temp_min': 24.94,
                'temp_max': 26,
                'pressure': 1014,
                'sea_level': 1014,
                'grnd_level': 1011,
                'humidity': 67,
                'temp_kf': 1.06,
            },
            'weather': [
                {
                    'id': 802,
                    'main': 'Clouds',
                    'description': 'nuvens dispersas',
                    'icon': '03n',
                }
            ],
            'clouds': {'all': 28},
            'wind': {'speed': 5.4, 'deg': 142, 'gust': 9.82},
            'visibility': 10000,
            'pop': 0,
            'sys': {'pod': 'n'},
            'dt_txt': '2024-09-24 21:00:00',
        },
        {
            'dt': 1727222400,
            'main': {
                'temp': 24.78,
                'feels_like': 25.35,
                'temp_min': 24.78,
                'temp_max': 24.78,
                'pressure': 1015,
                'sea_level': 1015,
                'grnd_level': 1012,
                'humidity': 78,
                'temp_kf': 0,
            },
            'weather': [
                {
                    'id': 800,
                    'main': 'Clear',
                    'description': 'céu limpo',
                    'icon': '01n',
                }
            ],
            'clouds': {'all': 3},
            'wind': {'speed': 6.15, 'deg': 127, 'gust': 10.69},
            'visibility': 10000,
            'pop': 0,
            'sys': {'pod': 'n'},
            'dt_txt': '2024-09-25 00:00:00',
        },
        {
            'dt': 1727233200,
            'main': {
                'temp': 24.55,
                'feels_like': 25.15,
                'temp_min': 24.55,
                'temp_max': 24.55,
                'pressure': 1014,
                'sea_level': 1014,
                'grnd_level': 1011,
                'humidity': 80,
                'temp_kf': 0,
            },
            'weather': [
                {
                    'id': 801,
                    'main': 'Clouds',
                    'description': 'algumas nuvens',
                    'icon': '02n',
                }
            ],
            'clouds': {'all': 12},
            'wind': {'speed': 6.22, 'deg': 133, 'gust': 9.92},
            'visibility': 10000,
            'pop': 0,
            'sys': {'pod': 'n'},
            'dt_txt': '2024-09-25 03:00:00',
        },
        {
            'dt': 1727244000,
            'main': {
                'temp': 24.17,
                'feels_like': 24.76,
                'temp_min': 24.17,
                'temp_max': 24.17,
                'pressure': 1013,
                'sea_level': 1013,
                'grnd_level': 1010,
                'humidity': 81,
                'temp_kf': 0,
            },
            'weather': [
                {
                    'id': 500,
                    'main': 'Rain',
                    'description': 'chuva leve',
                    'icon': '10n',
                }
            ],
            'clouds': {'all': 17},
            'wind': {'speed': 5.67, 'deg': 133, 'gust': 9.78},
            'visibility': 10000,
            'pop': 0.2,
            'rain': {'3h': 0.19},
            'sys': {'pod': 'n'},
            'dt_txt': '2024-09-25 06:00:00',
        },
        {
            'dt': 1727254800,
            'main': {
                'temp': 24.26,
                'feels_like': 24.8,
                'temp_min': 24.26,
                'temp_max': 24.26,
                'pressure': 1014,
                'sea_level': 1014,
                'grnd_level': 1011,
                'humidity': 79,
                'temp_kf': 0,
            },
            'weather': [
                {
                    'id': 500,
                    'main': 'Rain',
                    'description': 'chuva leve',
                    'icon': '10d',
                }
            ],
            'clouds': {'all': 33},
            'wind': {'speed': 5.58, 'deg': 137, 'gust': 9.46},
            'visibility': 10000,
            'pop': 0.2,
            'rain': {'3h': 0.26},
            'sys': {'pod': 'd'},
            'dt_txt': '2024-09-25 09:00:00',
        },
        {
            'dt': 1727265600,
            'main': {
                'temp': 27.53,
                'feels_like': 28.78,
                'temp_min': 27.53,
                'temp_max': 27.53,
                'pressure': 1015,
                'sea_level': 1015,
                'grnd_level': 1013,
                'humidity': 60,
                'temp_kf': 0,
            },
            'weather': [
                {
                    'id': 802,
                    'main': 'Clouds',
                    'description': 'nuvens dispersas',
                    'icon': '03d',
                }
            ],
            'clouds': {'all': 26},
            'wind': {'speed': 6.7, 'deg': 132, 'gust': 8.46},
            'visibility': 10000,
            'pop': 0,
            'sys': {'pod': 'd'},
            'dt_txt': '2024-09-25 12:00:00',
        },
        {
            'dt': 1727276400,
            'main': {
                'temp': 28.81,
                'feels_like': 29.77,
                'temp_min': 28.81,
                'temp_max': 28.81,
                'pressure': 1013,
                'sea_level': 1013,
                'grnd_level': 1011,
                'humidity': 53,
                'temp_kf': 0,
            },
            'weather': [
                {
                    'id': 802,
                    'main': 'Clouds',
                    'description': 'nuvens dispersas',
                    'icon': '03d',
                }
            ],
            'clouds': {'all': 30},
            'wind': {'speed': 6.78, 'deg': 128, 'gust': 8.69},
            'visibility': 10000,
            'pop': 0,
            'sys': {'pod': 'd'},
            'dt_txt': '2024-09-25 15:00:00',
        },
        {
            'dt': 1727287200,
            'main': {
                'temp': 27.16,
                'feels_like': 28.86,
                'temp_min': 27.16,
                'temp_max': 27.16,
                'pressure': 1012,
                'sea_level': 1012,
                'grnd_level': 1009,
                'humidity': 67,
                'temp_kf': 0,
            },
            'weather': [
                {
                    'id': 801,
                    'main': 'Clouds',
                    'description': 'algumas nuvens',
                    'icon': '02d',
                }
            ],
            'clouds': {'all': 22},
            'wind': {'speed': 6.46, 'deg': 127, 'gust': 8.56},
            'visibility': 10000,
            'pop': 0,
            'sys': {'pod': 'd'},
            'dt_txt': '2024-09-25 18:00:00',
        },
        {
            'dt': 1727298000,
            'main': {
                'temp': 24.84,
                'feels_like': 25.44,
                'temp_min': 24.84,
                'temp_max': 24.84,
                'pressure': 1013,
                'sea_level': 1013,
                'grnd_level': 1010,
                'humidity': 79,
                'temp_kf': 0,
            },
            'weather': [
                {
                    'id': 801,
                    'main': 'Clouds',
                    'description': 'algumas nuvens',
                    'icon': '02n',
                }
            ],
            'clouds': {'all': 12},
            'wind': {'speed': 5.71, 'deg': 124, 'gust': 9.81},
            'visibility': 10000,
            'pop': 0,
            'sys': {'pod': 'n'},
            'dt_txt': '2024-09-25 21:00:00',
        },
        {
            'dt': 1727308800,
            'main': {
                'temp': 24.87,
                'feels_like': 25.5,
                'temp_min': 24.87,
                'temp_max': 24.87,
                'pressure': 1015,
                'sea_level': 1015,
                'grnd_level': 1012,
                'humidity': 80,
                'temp_kf': 0,
            },
            'weather': [
                {
                    'id': 500,
                    'main': 'Rain',
                    'description': 'chuva leve',
                    'icon': '10n',
                }
            ],
            'clouds': {'all': 19},
            'wind': {'speed': 6.77, 'deg': 116, 'gust': 10.3},
            'visibility': 10000,
            'pop': 0.2,
            'rain': {'3h': 0.1},
            'sys': {'pod': 'n'},
            'dt_txt': '2024-09-26 00:00:00',
        },
        {
            'dt': 1727319600,
            'main': {
                'temp': 24.33,
                'feels_like': 24.83,
                'temp_min': 24.33,
                'temp_max': 24.33,
                'pressure': 1014,
                'sea_level': 1014,
                'grnd_level': 1012,
                'humidity': 77,
                'temp_kf': 0,
            },
            'weather': [
                {
                    'id': 802,
                    'main': 'Clouds',
                    'description': 'nuvens dispersas',
                    'icon': '03n',
                }
            ],
            'clouds': {'all': 27},
            'wind': {'speed': 6, 'deg': 129, 'gust': 9.01},
            'visibility': 10000,
            'pop': 0,
            'sys': {'pod': 'n'},
            'dt_txt': '2024-09-26 03:00:00',
        },
        {
            'dt': 1727330400,
            'main': {
                'temp': 24.86,
                'feels_like': 25.12,
                'temp_min': 24.86,
                'temp_max': 24.86,
                'pressure': 1014,
                'sea_level': 1014,
                'grnd_level': 1011,
                'humidity': 66,
                'temp_kf': 0,
            },
            'weather': [
                {
                    'id': 802,
                    'main': 'Clouds',
                    'description': 'nuvens dispersas',
                    'icon': '03n',
                }
            ],
            'clouds': {'all': 38},
            'wind': {'speed': 5.94, 'deg': 126, 'gust': 8.83},
            'visibility': 10000,
            'pop': 0,
            'sys': {'pod': 'n'},
            'dt_txt': '2024-09-26 06:00:00',
        },
        {
            'dt': 1727341200,
            'main': {
                'temp': 24.5,
                'feels_like': 24.86,
                'temp_min': 24.5,
                'temp_max': 24.5,
                'pressure': 1014,
                'sea_level': 1014,
                'grnd_level': 1011,
                'humidity': 71,
                'temp_kf': 0,
            },
            'weather': [
                {
                    'id': 804,
                    'main': 'Clouds',
                    'description': 'nublado',
                    'icon': '04d',
                }
            ],
            'clouds': {'all': 97},
            'wind': {'speed': 5.63, 'deg': 128, 'gust': 8.65},
            'visibility': 10000,
            'pop': 0,
            'sys': {'pod': 'd'},
            'dt_txt': '2024-09-26 09:00:00',
        },
        {
            'dt': 1727352000,
            'main': {
                'temp': 26.78,
                'feels_like': 27.81,
                'temp_min': 26.78,
                'temp_max': 26.78,
                'pressure': 1016,
                'sea_level': 1016,
                'grnd_level': 1013,
                'humidity': 60,
                'temp_kf': 0,
            },
            'weather': [
                {
                    'id': 804,
                    'main': 'Clouds',
                    'description': 'nublado',
                    'icon': '04d',
                }
            ],
            'clouds': {'all': 98},
            'wind': {'speed': 6.17, 'deg': 127, 'gust': 8.1},
            'visibility': 10000,
            'pop': 0,
            'sys': {'pod': 'd'},
            'dt_txt': '2024-09-26 12:00:00',
        },
        {
            'dt': 1727362800,
            'main': {
                'temp': 28.68,
                'feels_like': 29.72,
                'temp_min': 28.68,
                'temp_max': 28.68,
                'pressure': 1013,
                'sea_level': 1013,
                'grnd_level': 1011,
                'humidity': 54,
                'temp_kf': 0,
            },
            'weather': [
                {
                    'id': 802,
                    'main': 'Clouds',
                    'description': 'nuvens dispersas',
                    'icon': '03d',
                }
            ],
            'clouds': {'all': 38},
            'wind': {'speed': 6.59, 'deg': 119, 'gust': 7.6},
            'visibility': 10000,
            'pop': 0,
            'sys': {'pod': 'd'},
            'dt_txt': '2024-09-26 15:00:00',
        },
        {
            'dt': 1727373600,
            'main': {
                'temp': 27.43,
                'feels_like': 28.47,
                'temp_min': 27.43,
                'temp_max': 27.43,
                'pressure': 1012,
                'sea_level': 1012,
                'grnd_level': 1009,
                'humidity': 58,
                'temp_kf': 0,
            },
            'weather': [
                {
                    'id': 801,
                    'main': 'Clouds',
                    'description': 'algumas nuvens',
                    'icon': '02d',
                }
            ],
            'clouds': {'all': 23},
            'wind': {'speed': 6.17, 'deg': 124, 'gust': 7.54},
            'visibility': 10000,
            'pop': 0,
            'sys': {'pod': 'd'},
            'dt_txt': '2024-09-26 18:00:00',
        },
        {
            'dt': 1727384400,
            'main': {
                'temp': 25.04,
                'feels_like': 25.45,
                'temp_min': 25.04,
                'temp_max': 25.04,
                'pressure': 1014,
                'sea_level': 1014,
                'grnd_level': 1011,
                'humidity': 71,
                'temp_kf': 0,
            },
            'weather': [
                {
                    'id': 800,
                    'main': 'Clear',
                    'description': 'céu limpo',
                    'icon': '01n',
                }
            ],
            'clouds': {'all': 2},
            'wind': {'speed': 5.27, 'deg': 120, 'gust': 8.4},
            'visibility': 10000,
            'pop': 0,
            'sys': {'pod': 'n'},
            'dt_txt': '2024-09-26 21:00:00',
        },
        {
            'dt': 1727395200,
            'main': {
                'temp': 24.89,
                'feels_like': 25.31,
                'temp_min': 24.89,
                'temp_max': 24.89,
                'pressure': 1015,
                'sea_level': 1015,
                'grnd_level': 1012,
                'humidity': 72,
                'temp_kf': 0,
            },
            'weather': [
                {
                    'id': 800,
                    'main': 'Clear',
                    'description': 'céu limpo',
                    'icon': '01n',
                }
            ],
            'clouds': {'all': 1},
            'wind': {'speed': 6.05, 'deg': 108, 'gust': 9.52},
            'visibility': 10000,
            'pop': 0,
            'sys': {'pod': 'n'},
            'dt_txt': '2024-09-27 00:00:00',
        },
        {
            'dt': 1727406000,
            'main': {
                'temp': 24.52,
                'feels_like': 24.99,
                'temp_min': 24.52,
                'temp_max': 24.52,
                'pressure': 1014,
                'sea_level': 1014,
                'grnd_level': 1011,
                'humidity': 75,
                'temp_kf': 0,
            },
            'weather': [
                {
                    'id': 800,
                    'main': 'Clear',
                    'description': 'céu limpo',
                    'icon': '01n',
                }
            ],
            'clouds': {'all': 5},
            'wind': {'speed': 5.51, 'deg': 106, 'gust': 9},
            'visibility': 10000,
            'pop': 0,
            'sys': {'pod': 'n'},
            'dt_txt': '2024-09-27 03:00:00',
        },
        {
            'dt': 1727416800,
            'main': {
                'temp': 24.67,
                'feels_like': 25.1,
                'temp_min': 24.67,
                'temp_max': 24.67,
                'pressure': 1013,
                'sea_level': 1013,
                'grnd_level': 1010,
                'humidity': 73,
                'temp_kf': 0,
            },
            'weather': [
                {
                    'id': 802,
                    'main': 'Clouds',
                    'description': 'nuvens dispersas',
                    'icon': '03n',
                }
            ],
            'clouds': {'all': 49},
            'wind': {'speed': 5.46, 'deg': 108, 'gust': 9.52},
            'visibility': 10000,
            'pop': 0,
            'sys': {'pod': 'n'},
            'dt_txt': '2024-09-27 06:00:00',
        },
        {
            'dt': 1727427600,
            'main': {
                'temp': 25,
                'feels_like': 25.57,
                'temp_min': 25,
                'temp_max': 25,
                'pressure': 1014,
                'sea_level': 1014,
                'grnd_level': 1012,
                'humidity': 77,
                'temp_kf': 0,
            },
            'weather': [
                {
                    'id': 500,
                    'main': 'Rain',
                    'description': 'chuva leve',
                    'icon': '10d',
                }
            ],
            'clouds': {'all': 90},
            'wind': {'speed': 5.21, 'deg': 114, 'gust': 8.48},
            'visibility': 10000,
            'pop': 0.2,
            'rain': {'3h': 0.11},
            'sys': {'pod': 'd'},
            'dt_txt': '2024-09-27 09:00:00',
        },
        {
            'dt': 1727438400,
            'main': {
                'temp': 28.01,
                'feels_like': 29.46,
                'temp_min': 28.01,
                'temp_max': 28.01,
                'pressure': 1016,
                'sea_level': 1016,
                'grnd_level': 1013,
                'humidity': 60,
                'temp_kf': 0,
            },
            'weather': [
                {
                    'id': 500,
                    'main': 'Rain',
                    'description': 'chuva leve',
                    'icon': '10d',
                }
            ],
            'clouds': {'all': 88},
            'wind': {'speed': 5.73, 'deg': 117, 'gust': 7.26},
            'visibility': 10000,
            'pop': 0.2,
            'rain': {'3h': 0.13},
            'sys': {'pod': 'd'},
            'dt_txt': '2024-09-27 12:00:00',
        },
        {
            'dt': 1727449200,
            'main': {
                'temp': 28.59,
                'feels_like': 29.84,
                'temp_min': 28.59,
                'temp_max': 28.59,
                'pressure': 1014,
                'sea_level': 1014,
                'grnd_level': 1011,
                'humidity': 56,
                'temp_kf': 0,
            },
            'weather': [
                {
                    'id': 804,
                    'main': 'Clouds',
                    'description': 'nublado',
                    'icon': '04d',
                }
            ],
            'clouds': {'all': 99},
            'wind': {'speed': 5.55, 'deg': 113, 'gust': 6.52},
            'visibility': 10000,
            'pop': 0,
            'sys': {'pod': 'd'},
            'dt_txt': '2024-09-27 15:00:00',
        },
        {
            'dt': 1727460000,
            'main': {
                'temp': 27.84,
                'feels_like': 28.81,
                'temp_min': 27.84,
                'temp_max': 27.84,
                'pressure': 1012,
                'sea_level': 1012,
                'grnd_level': 1009,
                'humidity': 56,
                'temp_kf': 0,
            },
            'weather': [
                {
                    'id': 804,
                    'main': 'Clouds',
                    'description': 'nublado',
                    'icon': '04d',
                }
            ],
            'clouds': {'all': 96},
            'wind': {'speed': 5.09, 'deg': 112, 'gust': 6.29},
            'visibility': 10000,
            'pop': 0,
            'sys': {'pod': 'd'},
            'dt_txt': '2024-09-27 18:00:00',
        },
        {
            'dt': 1727470800,
            'main': {
                'temp': 25.15,
                'feels_like': 25.68,
                'temp_min': 25.15,
                'temp_max': 25.15,
                'pressure': 1013,
                'sea_level': 1013,
                'grnd_level': 1010,
                'humidity': 75,
                'temp_kf': 0,
            },
            'weather': [
                {
                    'id': 801,
                    'main': 'Clouds',
                    'description': 'algumas nuvens',
                    'icon': '02n',
                }
            ],
            'clouds': {'all': 17},
            'wind': {'speed': 4.83, 'deg': 114, 'gust': 7.9},
            'visibility': 10000,
            'pop': 0,
            'sys': {'pod': 'n'},
            'dt_txt': '2024-09-27 21:00:00',
        },
        {
            'dt': 1727481600,
            'main': {
                'temp': 24.84,
                'feels_like': 25.39,
                'temp_min': 24.84,
                'temp_max': 24.84,
                'pressure': 1014,
                'sea_level': 1014,
                'grnd_level': 1011,
                'humidity': 77,
                'temp_kf': 0,
            },
            'weather': [
                {
                    'id': 801,
                    'main': 'Clouds',
                    'description': 'algumas nuvens',
                    'icon': '02n',
                }
            ],
            'clouds': {'all': 19},
            'wind': {'speed': 4.75, 'deg': 103, 'gust': 8.03},
            'visibility': 10000,
            'pop': 0,
            'sys': {'pod': 'n'},
            'dt_txt': '2024-09-28 00:00:00',
        },
        {
            'dt': 1727492400,
            'main': {
                'temp': 24.42,
                'feels_like': 25.03,
                'temp_min': 24.42,
                'temp_max': 24.42,
                'pressure': 1013,
                'sea_level': 1013,
                'grnd_level': 1010,
                'humidity': 81,
                'temp_kf': 0,
            },
            'weather': [
                {
                    'id': 801,
                    'main': 'Clouds',
                    'description': 'algumas nuvens',
                    'icon': '02n',
                }
            ],
            'clouds': {'all': 17},
            'wind': {'speed': 4.5, 'deg': 97, 'gust': 8.12},
            'visibility': 10000,
            'pop': 0,
            'sys': {'pod': 'n'},
            'dt_txt': '2024-09-28 03:00:00',
        },
        {
            'dt': 1727503200,
            'main': {
                'temp': 24.38,
                'feels_like': 24.99,
                'temp_min': 24.38,
                'temp_max': 24.38,
                'pressure': 1012,
                'sea_level': 1012,
                'grnd_level': 1009,
                'humidity': 81,
                'temp_kf': 0,
            },
            'weather': [
                {
                    'id': 500,
                    'main': 'Rain',
                    'description': 'chuva leve',
                    'icon': '10n',
                }
            ],
            'clouds': {'all': 32},
            'wind': {'speed': 4.83, 'deg': 95, 'gust': 8.42},
            'visibility': 10000,
            'pop': 0.2,
            'rain': {'3h': 0.12},
            'sys': {'pod': 'n'},
            'dt_txt': '2024-09-28 06:00:00',
        },
        {
            'dt': 1727514000,
            'main': {
                'temp': 24.79,
                'feels_like': 25.39,
                'temp_min': 24.79,
                'temp_max': 24.79,
                'pressure': 1014,
                'sea_level': 1014,
                'grnd_level': 1011,
                'humidity': 79,
                'temp_kf': 0,
            },
            'weather': [
                {
                    'id': 500,
                    'main': 'Rain',
                    'description': 'chuva leve',
                    'icon': '10d',
                }
            ],
            'clouds': {'all': 78},
            'wind': {'speed': 4.75, 'deg': 107, 'gust': 7.48},
            'visibility': 10000,
            'pop': 0.2,
            'rain': {'3h': 0.18},
            'sys': {'pod': 'd'},
            'dt_txt': '2024-09-28 09:00:00',
        },
        {
            'dt': 1727524800,
            'main': {
                'temp': 27.07,
                'feels_like': 29.06,
                'temp_min': 27.07,
                'temp_max': 27.07,
                'pressure': 1015,
                'sea_level': 1015,
                'grnd_level': 1012,
                'humidity': 71,
                'temp_kf': 0,
            },
            'weather': [
                {
                    'id': 500,
                    'main': 'Rain',
                    'description': 'chuva leve',
                    'icon': '10d',
                }
            ],
            'clouds': {'all': 62},
            'wind': {'speed': 5.03, 'deg': 102, 'gust': 6.37},
            'visibility': 10000,
            'pop': 0.2,
            'rain': {'3h': 0.25},
            'sys': {'pod': 'd'},
            'dt_txt': '2024-09-28 12:00:00',
        },
        {
            'dt': 1727535600,
            'main': {
                'temp': 28.74,
                'feels_like': 30.6,
                'temp_min': 28.74,
                'temp_max': 28.74,
                'pressure': 1013,
                'sea_level': 1013,
                'grnd_level': 1010,
                'humidity': 60,
                'temp_kf': 0,
            },
            'weather': [
                {
                    'id': 500,
                    'main': 'Rain',
                    'description': 'chuva leve',
                    'icon': '10d',
                }
            ],
            'clouds': {'all': 79},
            'wind': {'speed': 5.48, 'deg': 100, 'gust': 6.77},
            'visibility': 10000,
            'pop': 0.26,
            'rain': {'3h': 0.29},
            'sys': {'pod': 'd'},
            'dt_txt': '2024-09-28 15:00:00',
        },
        {
            'dt': 1727546400,
            'main': {
                'temp': 27.83,
                'feels_like': 29.41,
                'temp_min': 27.83,
                'temp_max': 27.83,
                'pressure': 1011,
                'sea_level': 1011,
                'grnd_level': 1008,
                'humidity': 62,
                'temp_kf': 0,
            },
            'weather': [
                {
                    'id': 803,
                    'main': 'Clouds',
                    'description': 'nublado',
                    'icon': '04d',
                }
            ],
            'clouds': {'all': 53},
            'wind': {'speed': 5.28, 'deg': 104, 'gust': 6.89},
            'visibility': 10000,
            'pop': 0,
            'sys': {'pod': 'd'},
            'dt_txt': '2024-09-28 18:00:00',
        },
        {
            'dt': 1727557200,
            'main': {
                'temp': 25.27,
                'feels_like': 25.86,
                'temp_min': 25.27,
                'temp_max': 25.27,
                'pressure': 1013,
                'sea_level': 1013,
                'grnd_level': 1010,
                'humidity': 77,
                'temp_kf': 0,
            },
            'weather': [
                {
                    'id': 801,
                    'main': 'Clouds',
                    'description': 'algumas nuvens',
                    'icon': '02n',
                }
            ],
            'clouds': {'all': 23},
            'wind': {'speed': 4.66, 'deg': 96, 'gust': 8.22},
            'visibility': 10000,
            'pop': 0,
            'sys': {'pod': 'n'},
            'dt_txt': '2024-09-28 21:00:00',
        },
        {
            'dt': 1727568000,
            'main': {
                'temp': 25.7,
                'feels_like': 26.21,
                'temp_min': 25.7,
                'temp_max': 25.7,
                'pressure': 1015,
                'sea_level': 1015,
                'grnd_level': 1012,
                'humidity': 72,
                'temp_kf': 0,
            },
            'weather': [
                {
                    'id': 803,
                    'main': 'Clouds',
                    'description': 'nublado',
                    'icon': '04n',
                }
            ],
            'clouds': {'all': 51},
            'wind': {'speed': 5.87, 'deg': 101, 'gust': 8.58},
            'visibility': 10000,
            'pop': 0,
            'sys': {'pod': 'n'},
            'dt_txt': '2024-09-29 00:00:00',
        },
        {
            'dt': 1727578800,
            'main': {
                'temp': 24.74,
                'feels_like': 25.2,
                'temp_min': 24.74,
                'temp_max': 24.74,
                'pressure': 1013,
                'sea_level': 1013,
                'grnd_level': 1011,
                'humidity': 74,
                'temp_kf': 0,
            },
            'weather': [
                {
                    'id': 803,
                    'main': 'Clouds',
                    'description': 'nublado',
                    'icon': '04n',
                }
            ],
            'clouds': {'all': 73},
            'wind': {'speed': 5.91, 'deg': 109, 'gust': 9.41},
            'visibility': 10000,
            'pop': 0,
            'sys': {'pod': 'n'},
            'dt_txt': '2024-09-29 03:00:00',
        },
        {
            'dt': 1727589600,
            'main': {
                'temp': 24.37,
                'feels_like': 24.98,
                'temp_min': 24.37,
                'temp_max': 24.37,
                'pressure': 1013,
                'sea_level': 1013,
                'grnd_level': 1010,
                'humidity': 81,
                'temp_kf': 0,
            },
            'weather': [
                {
                    'id': 500,
                    'main': 'Rain',
                    'description': 'chuva leve',
                    'icon': '10n',
                }
            ],
            'clouds': {'all': 41},
            'wind': {'speed': 5.44, 'deg': 120, 'gust': 9.89},
            'visibility': 10000,
            'pop': 0.2,
            'rain': {'3h': 0.15},
            'sys': {'pod': 'n'},
            'dt_txt': '2024-09-29 06:00:00',
        },
        {
            'dt': 1727600400,
            'main': {
                'temp': 25.21,
                'feels_like': 25.61,
                'temp_min': 25.21,
                'temp_max': 25.21,
                'pressure': 1014,
                'sea_level': 1014,
                'grnd_level': 1011,
                'humidity': 70,
                'temp_kf': 0,
            },
            'weather': [
                {
                    'id': 500,
                    'main': 'Rain',
                    'description': 'chuva leve',
                    'icon': '10d',
                }
            ],
            'clouds': {'all': 22},
            'wind': {'speed': 5.83, 'deg': 112, 'gust': 9.18},
            'visibility': 10000,
            'pop': 0.2,
            'rain': {'3h': 0.12},
            'sys': {'pod': 'd'},
            'dt_txt': '2024-09-29 09:00:00',
        },
        {
            'dt': 1727611200,
            'main': {
                'temp': 28.44,
                'feels_like': 29.28,
                'temp_min': 28.44,
                'temp_max': 28.44,
                'pressure': 1015,
                'sea_level': 1015,
                'grnd_level': 1012,
                'humidity': 53,
                'temp_kf': 0,
            },
            'weather': [
                {
                    'id': 801,
                    'main': 'Clouds',
                    'description': 'algumas nuvens',
                    'icon': '02d',
                }
            ],
            'clouds': {'all': 17},
            'wind': {'speed': 6.72, 'deg': 115, 'gust': 9.44},
            'visibility': 10000,
            'pop': 0,
            'sys': {'pod': 'd'},
            'dt_txt': '2024-09-29 12:00:00',
        },
    ],
    'city': {
        'id': 3394023,
        'name': 'Natal',
        'coord': {'lat': -5.8054, 'lon': -35.2081},
        'country': 'BR',
        'population': 763043,
        'timezone': -10800,
        'sunrise': 1727165346,
        'sunset': 1727208979,
    },
}
